INSTALLED_APPS = ["languagetool"]

LT_URL = "http://localhost:9000/"

# Use plain StaticFilesStorage instead of CompressedManifestStaticFilesStorage
# during CI tests.  The manifest storage requires a pre-built staticfiles.json
# (generated by collectstatic), but CI runs setup --no-static which skips it.
# Without this override the ASGI child process crashes when servestatic resolves
# the staticfiles storage during middleware initialization.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    },
}
