name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LANGUAGETOOL_VERSION: 5.4
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: actions/checkout@v3
    - uses: nanasess/setup-chromedriver@master
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libjpeg-dev python3-dev python3-pip gettext zlib1g-dev git nodejs build-essential openjdk-11-jre
        wget https://languagetool.org/download/LanguageTool-${LANGUAGETOOL_VERSION}.zip
        unzip LanguageTool-${LANGUAGETOOL_VERSION}.zip
        cd fiduswriter
        mv ../ci/configuration.py ./
        pip install requests[security]
        pip install coverage
        pip install coveralls
        pip install packaging
        pip install webdriver-manager
        pip install selenium
        pip install wheel
        pip install pip --upgrade
        if grep version pyproject.toml | grep -q "dev";
          then pip install https://github.com/fiduswriter/fiduswriter/archive/develop.zip;
          else pip install https://github.com/fiduswriter/fiduswriter/archive/main.zip;
        fi
        coverage run $(which fiduswriter) setup --no-static
    - name: Run test languagetool
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 8
        max_attempts: 3
        retry_on: error
        command: |
          cd LanguageTool-${LANGUAGETOOL_VERSION}
          java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 9000 &
          cd ../fiduswriter
          coverage run $(which fiduswriter) test languagetool
    - name: Coveralls
      run: |
          cd fiduswriter
          coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      run: curl "https://coveralls.io/webhook?repo_token=${{ secrets.GITHUB_TOKEN }}&repo_name=${{ github.repository }}" -d "payload[build_num]=${{ github.run_id }}&payload[status]=done"
